[package]
name = "aoc2017-rust"
version = "0.1.0"
authors = ["Martin Gabel <martin.gabel@becker-antriebe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"